language: cpp
compiler: gcc
script: make && make test
#could add more notifications here.

before_install:
  -pip install --user cpp-coveralls
  
after_success:
  -coveralls --include "balanced.cpp" --gcov-options '\-lp'
